// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj8TlVfH4iVLMbIBDwsjUfa701zACA1To',
    appId: '1:250816325113:web:8b63731fc1c226bf3a8928',
    messagingSenderId: '250816325113',
    projectId: 'distribution-7aa99',
    authDomain: 'distribution-7aa99.firebaseapp.com',
    storageBucket: 'distribution-7aa99.appspot.com',
    measurementId: 'G-PLKFRHWNTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb7auDlKExnen9hp6Ldp_kDDPdJ2PGAgw',
    appId: '1:250816325113:android:43a3163d3f9dedfb3a8928',
    messagingSenderId: '250816325113',
    projectId: 'distribution-7aa99',
    storageBucket: 'distribution-7aa99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDERxZIrc64Kk4FAVtqvK2R2A206yrpcN0',
    appId: '1:250816325113:ios:9e326a22fb0c11173a8928',
    messagingSenderId: '250816325113',
    projectId: 'distribution-7aa99',
    storageBucket: 'distribution-7aa99.appspot.com',
    iosBundleId: 'com.example.firebaseAppDistribution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDERxZIrc64Kk4FAVtqvK2R2A206yrpcN0',
    appId: '1:250816325113:ios:9e326a22fb0c11173a8928',
    messagingSenderId: '250816325113',
    projectId: 'distribution-7aa99',
    storageBucket: 'distribution-7aa99.appspot.com',
    iosBundleId: 'com.example.firebaseAppDistribution',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj8TlVfH4iVLMbIBDwsjUfa701zACA1To',
    appId: '1:250816325113:web:2374c2fd1c4dbc8b3a8928',
    messagingSenderId: '250816325113',
    projectId: 'distribution-7aa99',
    authDomain: 'distribution-7aa99.firebaseapp.com',
    storageBucket: 'distribution-7aa99.appspot.com',
    measurementId: 'G-LYXYL34ZCF',
  );
}
