name: Firebase Distribution

on: 
  push:
    branches:
      - main

jobs:
  firebase-distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH

      - name: Build Flutter App
        run: flutter build apk

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}  # Your Firebase App ID
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}  # The content of your service account key
          groups: 'your-testers-group'  # Change to your tester group
          file: build/app/outputs/flutter-apk/app-release.apk  # Path to your built APK
          releaseNotes: 'Release notes here'
